specVersion: "0.0.1"
description: "This subquery indexes bond,reward and slash of each block, summarize total earning of an account"
repository: "https://github.com/onfinality-io/subql-examples"

schema: "./schema.graphql"

network:
  endpoint: "wss://polkadot.api.onfinality.io/ws?apikey=e3362f7e-9403-4382-99f2-26c824e7df39"

dataSources:
  - name: runtime
    kind: substrate/Runtime
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
