specVersion: "0.0.1"
description: "This subquery indexes bond,reward and slash of each block, summarize total earning of an account"
repository: "https://github.com/onfinality-io/subql-examples"

schema: "./schema.graphql"

network:
  endpoint: "wss://polkadot.api.onfinality.me/ws?apikey=54a5d840-d6ff-4967-9eeb-52343c00f41c"

dataSources:
  - name: runtime
    kind: substrate/Runtime
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
