version: '3'

services:
  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  subquery-query:
    image: onfinality/subql-query:v0.2.0
    ports:
      - "3000:3000"
    depends_on:
      - "postgres"
    restart: always
    command:
      - -n=block-timestamp
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_POST: 5432

  subquery-node:
    image: onfinality/subql-node:v0.7.0
    depends_on:
      - "postgres"
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_POST: 5432
    volumes:
      - ./:/app
    command:
      - -f=/app
      - --subquery-name=block-timestamp

